### ISSUE TITLE
About the parameter setting of training command 

### ISSUE THREAD

**Issue by zhouweii234** [hkchengrex/STCN#15]
I use the command `CUDA_VISIBLE_DEVICES=0,3 OMP_NUM_THREADS=4 python -m torch.distributed.launch --nproc_per_node=2 train.py --id retrain_s0 --stage 0` to train the model, but an error occurred.
The error message is as follows：

CUDA Device count:  2
CUDA Device count:  2
I am rank 0 in this world of size 2!
I will take the role of logging!
I am rank 1 in this world of size 2!
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    logger = TensorboardLogger(para['id'], long_id)
  File "/root/projects/code/STCN/util/logger.py", line 46, in __init__
    repo = git.Repo(".")
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/git/repo/base.py", line 220, in __init__
    self.working_dir = self._working_tree_dir or self.common_dir  # type: Optional[PathLike]
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/git/repo/base.py", line 303, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    model = STCNModel(para, local_rank=local_rank, world_size=world_size).train()
  File "/root/projects/code/STCN/model/model.py", line 26, in __init__
    STCN(self.single_object).cuda(), 
  File "/root/projects/code/STCN/model/network.py", line 80, in __init__
    self.key_encoder = KeyEncoder()
  File "/root/projects/code/STCN/model/modules.py", line 129, in __init__
    resnet = models.resnet50(pretrained=True)
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torchvision/models/resnet.py", line 300, in resnet50
    return _resnet('resnet50', Bottleneck, [3, 4, 6, 3], pretrained, progress,
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torchvision/models/resnet.py", line 262, in _resnet
    state_dict = load_state_dict_from_url(model_urls[arch],
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/hub.py", line 528, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
Killing subprocess 24445
Killing subprocess 24446
Traceback (most recent call last):
  File "/root/miniconda3/envs/pytracking/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/pytracking/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/root/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/pytracking/bin/python', '-u', 'train.py', '--local_rank=1', '--id', 'retrain_s0', '--stage', '0']' returned non-zero exit status 1.

I don't set the parameter `master_ port` and keep the parameters `id` unchanged because I fail to understand the tutorial.
Do you know the cause of the problem, and could you kindly teach me how to set the parameter `master_ port` and `id` ?

**Comment by hkchengrex** [comment]
1. The error seems to come from `git`, which I used to log the commit id in tensorboard for tracking. You are probably using it in a non-git setting (e.g., `.git` damaged somehow). You can either recover the git info (`git clone` or otherwise) or just remove any references to `git` in the code.
2. `master_port` is a parameter of DDP. Read PyTorch's tutorial to learn more, but the idea is just to tie it to an unused port.
3. `id` is a unique identifier of an experiment. It is just the "name" of a run.

**Comment by zhouweii234** [comment]
I got it, thank you very much.

**Comment by zhouweii234** [comment]
I got it, thank you very much.
